export const CONFIG_REQUEST = 'CONFIG_REQUEST'
export const CONFIG_SUCCESS = 'CONFIG_SUCCESS'
export const CONFIG_FAILURE = 'CONFIG_FAILURE'

export default {
  CONFIG_REQUEST,
  CONFIG_SUCCESS,
  CONFIG_FAILURE
}
